title:              Data Analysis HandsOn Notes
email:              pkj.bhatt@yahoo.com
description:        This includes series of blogs on my way to learn and apply data science and AI.
author:             pankaj Bhatt
baseurl:            ""
url:                "https://pankaj2505.github.io"

# Social Profiles
twitter_username:   
github_username:    https://github.com/Pankaj2505
facebook_username:  
instagram_username:  
linkedin_username: https://www.linkedin.com/in/pkjbhatt/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter : rouge